steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/$PROJECT_ID/$_MATHGARAGE_ARTIFACT_REPO/mathfunctions-api:$SHORT_SHA', 'mathfunctions-api']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/$PROJECT_ID/$_MATHGARAGE_ARTIFACT_REPO/mathfunctions-api:$SHORT_SHA']

  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'mathfunctions-api', 
           '--image=us-central1-docker.pkg.dev/$PROJECT_ID/$_MATHGARAGE_ARTIFACT_REPO/mathfunctions-api:$SHORT_SHA', 
           '--region', 'us-central1', '--platform', 'managed', 
           '--allow-unauthenticated']

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/$_MATHGARAGE_ARTIFACT_REPO/mathfunctions-api:$SHORT_SHA
